name: CI
on:
  - pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and test
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Build Docker Image
        run: |
          docker build -t microserviceuser .
          docker images
